# https://domluna.github.io/JuliaFormatter.jl/stable/

style = "sciml"

always_for_in = true
annotate_untyped_fields_with_any = false
conditional_to_if = true
format_docstrings = true
join_lines_based_on_source = true
long_to_short_function_def = false
margin = 100
separate_kwargs_with_semicolon = true
short_to_long_function_def = true
surround_whereop_typeparameters = false
whitespace_in_kwargs = false
whitespace_ops_in_indices = false
whitespace_typedefs = false
yas_style_nesting = true
