name: Benchmark

on:
  pull_request:
    branches: [ main ]   # change if your default branch differs
  workflow_dispatch:     # allows manual triggering for PRs from forks

permissions:
  pull-requests: write    # needed to post comments

jobs:
  bench:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: ["1"] # could also add 1.10 (LTS), but not needed
    steps:
      - name: Benchmark PR with AirspeedVelocity
        uses: MilesCranmer/AirspeedVelocity.jl@action-v1.1.0
        with:
          julia-version: ${{ matrix.julia-version }}
          job-summary: 'false'
